name: "Help System"
slug: help
version: 2.0.0
triggers:
  slash: "/help"
  aliases: []
  input_mode: "inline"
reserved: true

requires:
  secrets: []
  capabilities: []

steps:
  - id: show-help
    type: transform
    template: |
      # Commands Cheat Sheet

      Here are the commands you can use in the chat:

      ## Fragment Commands
      - `/frag <content>` – Create a new fragment
      - `/recall <query>` – Search and recall fragments
      - `/bookmark` – Bookmark current conversation
      - `/link <url>` – Save a link as fragment

      ## Todo & Task Management
      - `/todo <task>` – Create a todo item
      - `/inbox` – View pending fragments

      ## Search & Discovery
      - `/search <query>` – Search fragments and content
      - `/help <section>` – Get help for specific commands

      ## Channel & Navigation
      - `/join <channel>` – Join or create a channel
      - `/channels` – List available channels
      - `/name <title>` – Set channel name

      ## Session Management  
      - `/session` – Manage current session
      - `/clear` – Clear chat history

      ## System Tools
      - `/settings` – Access system settings
      - `/news` – Get latest AI/tech news

      ## Orchestration Commands
      - `/sprint-list` (or `/sl`) – List all sprints with progress tracking
      - `/sprint-detail <code>` (or `/sd`) – Show sprint details and tasks
      - `/task-list [sprint]` (or `/tl`) – List active tasks (optionally filter by sprint)
      - `/backlog-list` (or `/bl`) – List backlog items and completed tasks
      - `/task-detail <id>` (or `/td`) – Show task details with full content
      - `/task-assign <task> <agent>` (or `/ta`) – Assign task to agent
      - `/agent-list` (or `/al`) – List all available agents

      **Tip**: Most commands work with or without arguments. Try them out!

  - id: show-panel
    type: response.panel
    with:
      type: "help"  
      panel_data:
        message: "{{ steps.show-help.output }}"