name: "Create Fragment Simple"
slug: frag-simple
version: 2.0.0
triggers:
  slash: "/frag-simple"
  aliases: []
  input_mode: "inline"
reserved: true

requires:
  secrets: []
  capabilities: ["fragment.create"]

steps:
  - id: check-message
    type: condition
    condition: "{{ ctx.identifier | default: '' | length > 0 }}"
    then:
      # Create the fragment
      - id: create-fragment
        type: fragment.create
        with:
          vault: "default"
          type: "log"
          message: "{{ ctx.identifier }}"
          source: "chat"
          metadata:
            aside: true
      
      - id: success-response
        type: notify
        with:
          message: "Fragment saved"
          level: "success"
          response_data:
            type: "frag"
            shouldShowSuccessToast: true
            fragments: []
    else:
      # Show error for missing message
      - id: error-response
        type: notify
        with:
          message: "No valid fragment detected. Please try `/frag Your message here...`"
          level: "error"
          response_data:
            type: "frag"
            shouldShowErrorToast: true