name: "List Channels"
slug: channels
version: 2.0.0
triggers:
  slash: "/channels"
  aliases: []
  input_mode: "inline"
reserved: true

requires:
  secrets: []
  capabilities: []

steps:
  - id: query-active-channels
    type: model.query
    with:
      model: "chat_session"
      conditions:
        - field: "vault_id"
          operator: "="
          value: "{{ ctx.vault_id }}"
      order: "last_activity_at DESC"
      limit: 25
  
  - id: check-channels-exist
    type: condition
    condition: "{{ steps.query-active-channels.output | length > 0 }}"
    then:
      - id: format-channels-list
        type: transform
        template: |
          # Active Channels ({{ steps.query-active-channels.output | length }})
          
          **Available channels in your workspace:**
          
          {% for session in steps.query-active-channels.output %}
          - `#{{ session.short_code }}` – {{ session.title | default: session.custom_name | default: 'Untitled' }} *(last activity: {{ session.last_activity_at | timeago | default: 'no activity' }})*{% if session.is_active %} 🟢{% endif %}
          {% endfor %}
          
          **Usage:**
          - Type `/join #c1` to join a specific channel
          - Use `/join <search>` to search for channels
      
      - id: show-channels-list
        type: response.panel
        with:
          type: "channels-list"
          panel_data:
            message: "{{ steps.format-channels-list.output }}"
            channels: "{{ steps.query-active-channels.output }}"
    else:
      - id: show-no-channels
        type: response.panel
        with:
          type: "channels-list"
          panel_data:
            message: |
              **No Active Channels**
              
              There are no active chat channels in the current context.
              
              Use `/session start` to create a new chat session.