name: "Open Settings"
slug: settings
version: 1.0.0
triggers:
  slash: "/settings"
  aliases: ["/preferences", "/config"]
  input_mode: "inline"
reserved: true

requires:
  secrets: []
  capabilities: []

steps:
  - id: open-settings
    type: notify
    with:
      message: "Opening Settings..."
      level: "info"
      panel_data:
        action: "navigate"
        url: "/settings"