name: "Routing Management"
slug: routing
version: 2.0.0
triggers:
  slash: "/routing"
  aliases: []
  input_mode: "inline"
reserved: true

requires:
  secrets: []
  capabilities: ["model.query", "model.create", "model.update", "model.delete"]

steps:
  # Always query routing rules first
  - id: query-routing-rules
    type: model.query
    with:
      model: "vault_routing_rule"
      order:
        field: "priority"
        direction: "asc"
  

  
  # Determine action and show appropriate response
  - id: show-response
    type: transform
    template: |
      {% if ctx.body == 'create' %}
        **Creating routing rule...**
        A new test routing rule will be created. (Feature in development)
      {% elsif ctx.body == 'list' or ctx.body == '' %}
        {% if steps.query-routing-rules.output | length > 0 %}
          🛣️ **Routing Rules ({{ steps.query-routing-rules.output | length }}):**
          {% for rule in steps.query-routing-rules.output %}
          - **{{ rule.name }}** ({{ rule.match_type }}: `{{ rule.match_value }}`) → Vault {{ rule.target_vault_id }}{% if rule.target_project_id %}, Project {{ rule.target_project_id }}{% endif %} {% if rule.is_active %}✅{% else %}❌{% endif %} [Priority: {{ rule.priority }}]
          {% endfor %}
        {% else %}
          No routing rules found. Use `/routing create` to add rules.
        {% endif %}
      {% else %}
        🛣️ **Routing Command Usage**
        
        **List Operations:**
        - `/routing` or `/routing list` - List all routing rules
        
        **Management Operations:**
        - `/routing create` - Create new test routing rule
        
        **Examples:**
        ```
        /routing list
        /routing create
        ```
      {% endif %}
  
  # Show panel with current data
  - id: show-panel
    type: response.panel
    with:
      type: "routing"
      panel_data:
        action: "{% if ctx.body == 'list' or ctx.body == '' %}list{% else %}help{% endif %}"
        message: "{{ steps.show-response.output }}"
        rules: "{{ steps.query-routing-rules.output }}"