name: "Pause Scheduled Task"
slug: schedule-pause
version: 1.0.0
triggers:
  slash: "/schedule:pause"
  input_mode: "inline"

requires:
  secrets: []
  capabilities: ["database.write"]

steps:
  - id: pause-schedule
    type: action
    action: "App\\Actions\\Commands\\ScheduleControlCommand"