name: "Todo Management (Deterministic)"
slug: todo
version: 3.0.0
triggers:
  slash: "/todo"
  aliases: ["/t", "/todos"]
  input_mode: "inline"
reserved: true

requires:
  secrets: []
  capabilities: ["text.parse", "fragment.create"]

steps:
  - id: parse-todo
    type: text.parse
    with:
      input: "{{ ctx.body }}"
      parser: "todo"
      rules:
        extract_due_date: true
        extract_priority: true
        extract_tags: true

  - id: create-fragment
    type: fragment.create
    with:
      type: "todo"
      title: "{{ steps.parse-todo.output.output.title }}"
      message: "{{ ctx.body }}"
      state:
        status: "{{ steps.parse-todo.output.output.status | default: 'open' }}"
        priority: "{{ steps.parse-todo.output.output.priority | default: 'medium' }}"
        due_at: "{{ steps.parse-todo.output.output.due_date }}"
        created_at: "{{ now }}"
      tags: "{{ steps.parse-todo.output.output.tags }}"
      metadata:
        command: "todo"
        created_via: "slash_command"
        deterministic_parsing: true
        parsing_time_ms: "{{ steps.parse-todo.parsing_time_ms }}"

  - id: notify
    type: notify
    with:
      message: "✅ Todo created: {{ steps.parse-todo.output.output.title }}"
      level: "success"