name: "Inbox Management (Unified)"
slug: inbox
version: 2.0.0
triggers:
  slash: "/inbox"
  aliases: ["/in"]
  input_mode: "inline"
reserved: true

requires:
  secrets: []
  capabilities: ["fragment.query"]

steps:
  - id: display-inbox-summary
    type: notify
    with:
      message: |
        📥 **Inbox Management**
        
        **API Documentation**: Use `/inbox api` to see API documentation.
        
        **Current Status**: Inbox contains pending fragments
        **View Options**:
        - Use `/api/inbox` endpoint to view pending fragments
        - Access fragments through the web interface
        - Filter by status, type, or other criteria
        
        **Quick Actions**:
        - View pending: `GET /api/inbox?status=pending`
        - Accept fragment: `POST /api/inbox/{id}/accept`
        - Reject fragment: `POST /api/inbox/{id}/reject`
        
        **API Reference**:
        - **Endpoint**: `GET /api/inbox`
        - **Parameters**: status, type, limit
        - **Response**: JSON array of fragment objects
      level: "info"
    else:
      - id: query-pending
        type: fragment.query
        with:
          type: "todo"
          filters:
            state.status: "open"
          limit: 20
          order: "created_at desc"
          with_relations: ["type"]

      - id: display-pending
        type: response.panel
        with:
          type: "inbox"
          message: "📥 Found pending items in your inbox"
          shouldOpenPanel: true
          panel_data:
            action: "pending"
            type: "pending"
            fragments: "{{ steps.query-pending.output.fragments }}"