name: "Show Schedule Details"
slug: schedule-detail
version: 1.0.0
triggers:
  slash: "/schedule:detail"
  input_mode: "inline"

requires:
  secrets: []
  capabilities: ["database.read"]

steps:
  - id: show-schedule-detail
    type: action
    action: "App\\Actions\\Commands\\ScheduleDetailCommand"