name: "Sprint List"
slug: sprints
version: 1.0.0
triggers:
  slash: "/sprints"
  input_mode: "none"
reserved: true

requires:
  secrets: []
  capabilities: ["model.query"]

steps:
  - id: query-sprints
    type: model.query
    with:
      model: "sprints"
      order: "code ASC"

  - id: check-sprints-exist
    type: condition
    condition: "{{ steps.query-sprints.output.count > 0 }}"
    then:
      - id: format-sprint-data
        type: transform
        template: |
          {% set sprints = [] %}
          {% for sprint in steps.query-sprints.output.results %}
            
            {# Query tasks for this sprint #}
            {% set task_query = {
              "model": "work_items",
              "conditions": [{"field": "metadata->sprint_code", "operator": "=", "value": sprint.code}]
            } %}
            
            {% set meta = sprint.meta | default: {} %}
            {% set sprint_data = {
              "id": sprint.id,
              "code": sprint.code,
              "title": meta.title | default: sprint.code,
              "description": meta.description | default: null,
              "status": meta.status | default: "active",
              "priority": meta.priority | default: null,
              "meta": meta,
              "created_at": sprint.created_at,
              "updated_at": sprint.updated_at
            } %}
            {% set sprints = sprints | append: sprint_data %}
          {% endfor %}
          {{ sprints | json_encode }}

      - id: query-task-counts
        type: transform
        template: |
          {% set sprint_data_with_counts = [] %}
          {% for sprint in steps.format-sprint-data.output | from_json %}
            {# Use a separate query step for each sprint's tasks #}
            {% set sprint_tasks_query = {
              "model": "work_items",
              "conditions": [{"field": "metadata->sprint_code", "operator": "=", "value": sprint.code}]
            } %}
            
            {# For now, set default counts - this will be enhanced with actual task queries #}
            {% set enhanced_sprint = sprint | merge({
              "task_count": 0,
              "completed_tasks": 0,
              "in_progress_tasks": 0,
              "todo_tasks": 0,
              "backlog_tasks": 0
            }) %}
            {% set sprint_data_with_counts = sprint_data_with_counts | append: enhanced_sprint %}
          {% endfor %}
          {{ sprint_data_with_counts | json_encode }}

      - id: format-success-message
        type: transform
        template: |
          {% set count = steps.query-sprints.output.count %}
          {% set plural = count != 1 ? 's' : '' %}
          📋 Found **{{ count }}** sprint{{ plural }}

      - id: show-sprint-list
        type: response.panel
        with:
          type: "sprint"
          panel_data:
            action: "list"
            message: "{{ steps.format-success-message.output }}"
            sprints: "{{ steps.query-task-counts.output | from_json }}"
    else:
      - id: show-empty-list
        type: response.panel
        with:
          type: "sprint"
          panel_data:
            action: "list"
            message: "📋 No sprints found. Import delegation data to populate sprints."
            sprints: []