name: "Accept Inbox Fragment"
slug: accept
version: 1.0.0
triggers:
  slash: "/accept"
  aliases: ["/approve"]
  input_mode: "inline"
reserved: true

requires:
  secrets: []
  capabilities: ["fragment.update"]

steps:
  - id: parse-fragment-id
    type: transform
    template: |
      {{ ctx.body | default: ctx.fragment_id | trim }}

  - id: accept-instruction
    type: transform
    template: |
      Fragment ID: {{ ctx.body | default: ctx.fragment_id }}
      
      Use API endpoint POST /api/inbox/{fragment_id}/accept to accept this fragment.
      
      Optional edits can be provided in request body.

  - id: notify-instruction
    type: notify
    with:
      message: "{{ steps.accept-instruction.output }}"
      level: "info"