name: "Open Type System Management"
slug: types-ui
version: 1.0.0
triggers:
  slash: "/types"
  aliases: ["/type-system", "/typepacks"]
  input_mode: "inline"
reserved: true

requires:
  secrets: []
  capabilities: ["fragment.read"]

steps:
  - id: open-types-ui
    type: notify
    with:
      message: "Opening Type System Management Interface..."
      level: "info"
      panel_data:
        action: "open_modal"
        modal_type: "types"