name: "Resume Scheduled Task"
slug: schedule-resume
version: 1.0.0
triggers:
  slash: "/schedule:resume"
  input_mode: "inline"

requires:
  secrets: []
  capabilities: ["database.write"]

steps:
  - id: resume-schedule
    type: action
    action: "App\\Actions\\Commands\\ScheduleControlCommand"