# Backlog for Tools & Agents Foundation
epic: "Deterministic Tooling & Agent Foundations"
owner: "ProjectManagerAgent"
status: "planned"

tasks:
  - id: TSDK-001
    title: "Tool SDK & Registry (contracts, scopes, telemetry middleware)"
    desc: "Define ToolContract interface, registry, versioning, scopes, telemetry hooks."
    deliverables:
      - "ToolContract PHP interface + base middleware"
      - "ToolRegistry with JSON schema loader"
      - "Scopes & quotas config file"
    acceptance:
      - "Tools can declare input/output schemas"
      - "Registry lists all tools + versions"
      - "Telemetry logs tool name, version, scope, duration, outcome"
    effort: "M"
    risk: "Low"

  - id: DBQ-010
    title: "DB.Query v1 + SavedQuery"
    desc: "Laravel service + Prism function + internal API; boosts + explain."
    deliverables:
      - "DbQueryService with filter ops + fulltext"
      - "SavedQuery model/migration"
      - "Prism tool binding + internal endpoint"
    dependencies: [TSDK-001]
    acceptance:
      - "Query with filters/search/order/limit"
      - "Explain block included"
      - "Saved queries can be listed/run by id"
    effort: "L"
    risk: "Medium"

  - id: EXP-020
    title: "Exporters v1 + Artifacts Registry"
    desc: "Export md/txt/json/csv/xlsx; register artifacts with hashes and signed-download."
    deliverables:
      - "ExporterService with adapters"
      - "Artifacts table + model"
      - "Signed download routes + previews"
    dependencies: [TSDK-001, DBQ-010]
    acceptance:
      - "Exports reproducible with recorded inputs"
      - "Artifacts can be listed & downloaded"
    effort: "L"
    risk: "Medium"

  - id: PDF-025
    title: "PDF Adapter + Templating"
    desc: "Deterministic PDF via wkhtmltopdf or Dompdf; template library."
    dependencies: [EXP-020]
    acceptance:
      - "PDF export exists for list/detail reports"
      - "Template selection works by name/path"
    effort: "M"
    risk: "Low"

  - id: MEM-030
    title: "Agent Memory v1 (notes/decisions/vectors + rollups)"
    desc: "Short-term & long-term memory tables + tools (write/search/rollup)."
    deliverables:
      - "agent_notes, agent_decisions tables"
      - "memory.write/search/rollup tools"
      - "weekly rollup cron"
    dependencies: [TSDK-001]
    acceptance:
      - "LLM can store/retrieve decisions & notes with scope/tags"
      - "Rollups reduce per-run context size"
    effort: "M"
    risk: "Medium"

  - id: PRM-040
    title: "Prompt Orchestrator v1"
    desc: "Assemble system prompt dynamically with context, tools, memory; A/B variants."
    dependencies: [MEM-030, TSDK-001]
    acceptance:
      - "Runs generate a prompt with hashes + variant label"
      - "Telemetry records prompt, tools, outcomes"
    effort: "M"
    risk: "Medium"

  - id: PMG-050
    title: "Work Items + Kanban + Sprints"
    desc: "Unified work_items model, events log, sprints; minimal Kanban UI + slash commands."
    acceptance:
      - "Create epic/story/task/bug/spike/decision"
      - "Move through configurable kanban states"
      - "Events show comments/status/tool logs"
    effort: "L"
    risk: "Medium"

  - id: OPS-060
    title: "shell.exec (safe) + fs.* + diff.apply"
    desc: "Allowlisted shell, deterministic diff/apply, approvals, artifacts for patches."
    acceptance:
      - "Dry-run plans required for mutations"
      - "Approval gate applied for risky scopes"
    effort: "M"
    risk: "High"

  - id: OPS-065
    title: "repo.git + scheduler + notify"
    desc: "Repo interactions, scheduled tasks, system notifications."
    acceptance:
      - "Commit/diff/patch with artifacts"
      - "runLater/runEvery working with telemetry"
    effort: "M"
    risk: "Medium"

  - id: BRG-070
    title: "MCP Bridge (subset)"
    desc: "Expose read-only + low-risk tools to external clients via MCP."
    acceptance:
      - "Contracts surfaced over MCP with auth"
      - "High-risk tools excluded by default"
    effort: "S"
    risk: "Low"

  - id: UX-080
    title: "Runbooks + Plan→Approve→Apply pattern"
    desc: "Saved multi-tool sequences with approval and rollback notes."
    acceptance:
      - "Runbook can be executed with params"
      - "Produces plan artifact prior to apply"
    effort: "M"
    risk: "Medium"

  - id: INT-090
    title: "Decision Journal Automation + Weekly Rollups"
    desc: "Auto-extract decisions from chats/tools and summarize weekly per project."
    dependencies: [MEM-030]
    acceptance:
      - "Decisions linked to work_items and artifacts"
      - "Weekly rollups generated and pinned"
    effort: "S"
    risk: "Low"

  - id: CTX-095
    title: "Context Hints Cache (Top-20 per agent/project)"
    desc: "Daily refresh of key facts to reduce token usage and latency."
    dependencies: [MEM-030, PRM-040]
    effort: "S"
    risk: "Low"
