name: "Task List"
slug: tasks
version: 1.0.0
triggers:
  slash: "/tasks"
  input_mode: "inline"
reserved: true

requires:
  secrets: []
  capabilities: ["model.query"]

steps:
  - id: extract-sprint-filter
    type: transform
    template: "{{ ctx.body | trim | default: '' }}"

  - id: normalize-sprint-code
    type: condition
    condition: "{{ steps.extract-sprint-filter.output != '' }}"
    then:
      - id: process-sprint-code
        type: transform
        template: |
          {% set code = steps.extract-sprint-filter.output | trim %}
          {% if code | regex_test: '^\\d+$' %}
            SPRINT-{{ code | str_pad_left: 2, '0' }}
          {% elif code | regex_test: '^(?:sprint-)?\\d+$' %}
            {% set matches = code | regex_extract: '^(?:sprint-)?(\\d+)$' %}
            SPRINT-{{ matches.0 | str_pad_left: 2, '0' }}
          {% else %}
            {{ code | upper }}
          {% endif %}
    else:
      - id: process-sprint-code
        type: transform
        template: ""

  - id: query-tasks
    type: model.query
    with:
      model: "work_items"
      conditions: |
        {% if steps.process-sprint-code.output != '' %}
          [{"field": "metadata->sprint_code", "operator": "=", "value": "{{ steps.process-sprint-code.output }}"}]
        {% else %}
          [{"field": "metadata->sprint_code", "operator": "!=", "value": null}]
        {% endif %}
      order: |
        [
          {"sql": "CASE WHEN status = 'todo' THEN 1 WHEN status = 'backlog' THEN 2 ELSE 3 END"},
          {"field": "created_at", "direction": "desc"}
        ]
      limit: 50
      with_relations: ["assignedAgent"]

  - id: check-tasks-exist
    type: condition
    condition: "{{ steps.query-tasks.output.count > 0 }}"
    then:
      - id: format-task-data
        type: transform
        template: |
          {% set tasks = [] %}
          {% for task in steps.query-tasks.output.results %}
            {% set metadata = task.metadata | default: {} %}
            {% set task_data = {
              "id": task.id,
              "task_code": metadata.task_code | default: task.id,
              "task_name": metadata.task_name | default: "Untitled Task",
              "description": metadata.description | default: null,
              "sprint_code": metadata.sprint_code | default: null,
              "status": task.status,
              "delegation_status": task.delegation_status,
              "priority": task.priority,
              "agent_recommendation": metadata.agent_recommendation | default: null,
              "current_agent": (task.assignee_type == "agent" and task.assignedAgent) ? task.assignedAgent.name : null,
              "estimate_text": metadata.estimate_text | default: null,
              "estimated_hours": task.estimated_hours,
              "tags": task.tags | default: [],
              "has_content": {
                "agent": task.agent_content != null and task.agent_content != "",
                "plan": task.plan_content != null and task.plan_content != "",
                "context": task.context_content != null and task.context_content != "",
                "todo": task.todo_content != null and task.todo_content != "",
                "summary": task.summary_content != null and task.summary_content != ""
              },
              "created_at": task.created_at,
              "updated_at": task.updated_at,
              "completed_at": task.completed_at
            } %}
            {% set tasks = tasks | append: task_data %}
          {% endfor %}
          {{ tasks | json_encode }}

      - id: format-success-message
        type: transform
        template: |
          {% set count = steps.query-tasks.output.count %}
          {% set plural = count != 1 ? 's' : '' %}
          {% if steps.process-sprint-code.output != '' %}
            📋 Found **{{ count }}** task{{ plural }} for sprint: {{ steps.process-sprint-code.output }}
          {% else %}
            📋 Found **{{ count }}** task{{ plural }}
          {% endif %}

      - id: show-task-list
        type: response.panel
        with:
          type: "task"
          panel_data:
            action: "list"
            message: "{{ steps.format-success-message.output }}"
            tasks: "{{ steps.format-task-data.output | from_json }}"
            sprint_filter: "{{ steps.extract-sprint-filter.output }}"
    else:
      - id: format-empty-message
        type: transform
        template: |
          {% if steps.process-sprint-code.output != '' %}
            📋 No tasks found for sprint: {{ steps.process-sprint-code.output }}. Use `/sprint-list` to see available sprints.
          {% else %}
            📋 No sprint tasks found. Use `/tasks <sprint>` to filter by specific sprint.
          {% endif %}

      - id: show-empty-list
        type: response.panel
        with:
          type: "task"
          panel_data:
            action: "list"
            message: "{{ steps.format-empty-message.output }}"
            tasks: []
            sprint_filter: "{{ steps.extract-sprint-filter.output }}"