name: "Open Inbox Management Interface"
slug: inbox-ui
version: 1.0.0
triggers:
  slash: "/inbox"
  aliases: ["/pending", "/review"]
  input_mode: "inline"
reserved: true

requires:
  secrets: []
  capabilities: ["fragment.read", "fragment.update"]

steps:
  - id: open-inbox-ui
    type: notify
    with:
      message: "Opening Inbox Management Interface..."
      level: "info"
      panel_data:
        action: "open_modal"
        modal_type: "inbox"